# Generated by Django 3.2 on 2021-04-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='efarmapp.product'),
        ),
    ]
