# Generated by Django 3.2 on 2021-04-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0002_admin_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='product',
        ),
    ]
