# Generated by Django 3.2 on 2021-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0003_remove_admin_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='efarmapp.Product'),
        ),
    ]
