# Generated by Django 3.2 on 2021-04-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0007_productadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAdmin',
        ),
    ]
