# Generated by Django 3.2.5 on 2021-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarmapp', '0008_delete_productadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='session_token',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
